# Generated by Django 2.2 on 2019-05-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='sponsored_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members_only.Comment'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
