# Generated by Django 2.1.7 on 2019-03-24 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='members_only.Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='points_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_card',
            field=models.CharField(default='', max_length=100),
        ),
    ]
