# Generated by Django 2.1.7 on 2019-04-07 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0003_auto_20190324_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked_members',
            field=models.ManyToManyField(blank=True, related_name='_user_blocked_members_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
