# Generated by Django 2.2 on 2019-04-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0004_auto_20190407_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
