# Generated by Django 2.2 on 2019-04-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0006_user_last_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_verified',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
