# Generated by Django 2.2 on 2019-04-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0006_auto_20190427_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='urls',
            field=models.TextField(null=True),
        ),
    ]
