# Generated by Django 2.2 on 2019-04-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0007_auto_20190424_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='verification_charge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='members_only.VerificationCharge'),
        ),
    ]
