# Generated by Django 2.2 on 2019-04-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0007_auto_20190427_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='invitedby',
            new_name='invited_by',
        ),
    ]
