# Generated by Django 2.2 on 2019-04-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0008_auto_20190427_1846'),
    ]

    operations = [
    ]
