# Generated by Django 2.2 on 2019-04-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_only', '0010_merge_20190428_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_card',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer',
            field=models.CharField(max_length=50),
        ),
    ]
