# Generated by Django 2.2 on 2019-04-16 20:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccid', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('postid', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('visibility', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('invitedby', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('points', models.IntegerField(null=True)),
                ('usertype', models.CharField(max_length=50, null=True)),
                ('logintime', models.CharField(max_length=50, null=True)),
                ('logouttime', models.CharField(max_length=50, null=True)),
                ('createdData', models.DateTimeField(auto_now_add=True, null=True)),
                ('isVerified', models.BooleanField(default=True, null=True)),
                ('birthday', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
