# Generated by Django 2.2 on 2019-04-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_member_invitedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='invited_by',
        ),
    ]
