# Generated by Django 2.2 on 2019-04-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_member_invited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='member',
            name='logout_time',
        ),
    ]
