# Generated by Django 2.2 on 2019-04-22 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190422_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='current_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image_original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Image'),
        ),
    ]
